fix: _DevNull instance has no attribute 'isatty', sf 2682627
Fix for sourceforge id 2682627
"failure when parsing sys.stdin.isatty()"
https://sourceforge.net/support/tracker.php?aid=2682627

The error message generated was:

 Import failed (but source code parsing was successful).
     Error: AttributeError: _DevNull instance has no attribute 'isatty'

The special crafted object _DevNull is substituted with
open(os.devnull, "w")

(cherry picked from commit 269780a7686aaa8a919aa187a0d38d31125a5a51)

Signed-off-by: Johannes Dewender <github@JonnyJD.net>